In [2]:
!git clone https://github.com/pliang279/MultiBench.git

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/home/hi-born4/6th Sem/Applied Linear Algebra for Machine Learning/Tensor fusion network for multi modal sentiment analysis/myenv/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3577, in run_code
  File "/tmp/ipykernel_5889/2091075093.py", line 1, in <module>
    get_ipython().system('git clone https://github.com/pliang279/MultiBench.git')
  File "/home/hi-born4/6th Sem/Applied Linear Algebra for Machine Learning/Tensor fusion network for multi modal sentiment analysis/myenv/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 657, in system_piped
  File "/home/hi-born4/6th Sem/Applied Linear Algebra for Machine Learning/Tensor fusion network for multi modal sentiment analysis/myenv/lib/python3.11/site-packages/IPython/utils/_process_posix.py", line 125, in system
ModuleNotFoundError: No module named 'pexpect'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  Fi

In [2]:
%cd MultiBench

/home/hi-born4/6th Sem/Applied Linear Algebra for Machine Learning/Tensor fusion network for multi modal sentiment analysis/MultiBench


In [11]:
# %mkdir data
# %pip install gdown && gdown https://drive.google.com/u/0/uc?id=1szKIqO0t3Be_W91xvf6aYmsVVUa7wDHU

In [1]:
import torch
import sys
import os

ModuleNotFoundError: No module named 'torch'

In [13]:
from datasets.affect.get_data import get_dataloader
traindata, validdata, testdata = get_dataloader(
    'mosi_raw.pkl', robust_test=False, max_pad=True, data_type='mosi', max_seq_len=50)

ImportError: dynamic module does not define module export function (PyInit__torchtext)

In [ ]:
print(len(traindata)+len(validdata)+len(testdata))
print(len(testdata))


70
22


In [ ]:
for batch in traindata:
  audio,video,text,labels=batch

  break

In [ ]:
all_text = []
all_labels = []

for batch in traindata:
    text, labels = batch[-2:]
    all_text.append(text)
    all_labels.append(labels)

all_text = torch.cat(all_text, dim=0)
all_labels = torch.cat(all_labels, dim=0)


In [ ]:
print(len(all_text))

1283


In [ ]:
import torch


# Step 1: Round the floating-point values to the nearest integer
rounded_labels = torch.round(all_labels)

# Step 2: Clamp the values to the desired range [-2, 2]
clamped_labels = torch.clamp(rounded_labels, min=-2, max=2)

print(clamped_labels)


tensor([[-2.],
        [-2.],
        [ 2.],
        ...,
        [ 1.],
        [ 2.],
        [ 2.]])


In [ ]:
print(clamped_labels.shape)

torch.Size([1283, 1])


In [ ]:
num_classes = 5

# Initialize an empty tensor to store the one-hot encoded labels
one_hot_labels = torch.zeros((len(clamped_labels), num_classes))

# Iterate over each clamped label and set the corresponding index to 1
for i, label in enumerate(clamped_labels):
    # Extract the integer value from the tensor
    int_label = int(label.item())

    # Shift the label range from [-2, 2] to [0, 4]
    shifted_label = int_label + 2
    one_hot_labels[i][shifted_label] = 1

print(one_hot_labels)

tensor([[1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1.],
        ...,
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 1.]])


In [ ]:
from torch.utils.data import TensorDataset,DataLoader,ConcatDataset
new_dataset = TensorDataset(all_text, one_hot_labels)
train_text_dataloader = DataLoader(new_dataset, batch_size=32,shuffle=True)

In [ ]:
print(len(train_text_dataloader))

41


In [ ]:
all_text = []
all_labels = []

for batch in validdata:
    text, labels = batch[-2:]  # Text and labels are the last two components
    all_text.append(text)
    all_labels.append(labels)  # Round the labels

# Concatenate all batches
all_text = torch.cat(all_text, dim=0)
all_labels = torch.cat(all_labels, dim=0)
print(len(all_text))
rounded_labels = torch.round(all_labels)

# Step 2: Clamp the values to the desired range [-2, 2]
clamped_labels = torch.clamp(rounded_labels, min=-2, max=2)

print(clamped_labels)
num_classes = 5

# Initialize an empty tensor to store the one-hot encoded labels
one_hot_labels = torch.zeros((len(clamped_labels), num_classes))

# Iterate over each clamped label and set the corresponding index to 1
for i, label in enumerate(clamped_labels):
    # Extract the integer value from the tensor
    int_label = int(label.item())

    # Shift the label range from [-2, 2] to [0, 4]
    shifted_label = int_label + 2
    one_hot_labels[i][shifted_label] = 1

print(one_hot_labels)
from torch.utils.data import TensorDataset,DataLoader,ConcatDataset
new_dataset = TensorDataset(all_text, one_hot_labels)
val_text_dataloader = DataLoader(new_dataset, batch_size=32,shuffle=True)

214
tensor([[ 2.],
        [-1.],
        [ 0.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 0.],
        [ 1.],
        [-1.],
        [ 0.],
        [ 2.],
        [ 2.],
        [ 0.],
        [ 1.],
        [ 2.],
        [ 1.],
        [-1.],
        [ 2.],
        [ 0.],
        [ 1.],
        [-0.],
        [ 1.],
        [ 0.],
        [-2.],
        [-2.],
        [ 0.],
        [-2.],
        [-0.],
        [ 0.],
        [ 0.],
        [-2.],
        [-1.],
        [-2.],
        [-2.],
        [ 1.],
        [-2.],
        [ 1.],
        [ 1.],
        [-2.],
        [-2.],
        [-2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 1.],
        [-2.],
        [ 2.],
        [ 2.],
        [ 0.],
        [ 0.],
        [-1.],
        [ 2.],
        [ 1.],
        [ 1.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 1.],
        [-1.],
        [ 2.],
        [ 0.],
        [ 1.],
        [ 1.],
      

In [ ]:
print(len(val_text_dataloader))

7


In [ ]:
  all_text = []
  all_labels = []

  for batch in testdata:
      text, labels = batch[-2:]  # Text and labels are the last two components
      all_text.append(text)
      all_labels.append(labels)  # Round the labels

  # Concatenate all batches
  all_text = torch.cat(all_text, dim=0)
  all_labels = torch.cat(all_labels, dim=0)
  print(len(all_text))
  rounded_labels = torch.round(all_labels)

  # Step 2: Clamp the values to the desired range [-2, 2]
  clamped_labels = torch.clamp(rounded_labels, min=-2, max=2)

  print(clamped_labels)
  num_classes = 5

  # Initialize an empty tensor to store the one-hot encoded labels
  one_hot_labels = torch.zeros((len(clamped_labels), num_classes))

  # Iterate over each clamped label and set the corresponding index to 1
  for i, label in enumerate(clamped_labels):
      # Extract the integer value from the tensor
      int_label = int(label.item())

      # Shift the label range from [-2, 2] to [0, 4]
      shifted_label = int_label + 2
      one_hot_labels[i][shifted_label] = 1

  print(one_hot_labels)
  from torch.utils.data import TensorDataset,DataLoader,ConcatDataset
  new_dataset = TensorDataset(all_text, one_hot_labels)
  test_text_dataloader = DataLoader(new_dataset, batch_size=32,shuffle=True)

686
tensor([[-2.],
        [ 1.],
        [-2.],
        [-2.],
        [ 1.],
        [-2.],
        [-2.],
        [-1.],
        [-2.],
        [-2.],
        [-2.],
        [-2.],
        [-1.],
        [-2.],
        [-1.],
        [-2.],
        [ 0.],
        [-2.],
        [-2.],
        [-1.],
        [ 1.],
        [ 1.],
        [-1.],
        [-1.],
        [-2.],
        [-2.],
        [ 2.],
        [-2.],
        [-2.],
        [-2.],
        [-2.],
        [-0.],
        [ 1.],
        [ 2.],
        [ 2.],
        [-1.],
        [-2.],
        [-2.],
        [-2.],
        [-2.],
        [ 2.],
        [ 1.],
        [ 1.],
        [ 2.],
        [ 2.],
        [ 2.],
        [-1.],
        [-0.],
        [ 2.],
        [-2.],
        [-1.],
        [ 2.],
        [ 2.],
        [-1.],
        [-2.],
        [ 2.],
        [ 2.],
        [ 2.],
        [ 0.],
        [ 2.],
        [ 2.],
        [ 2.],
        [-1.],
        [ 1.],
        [ 0.],
        [-1.],
      

In [ ]:
print(len(test_text_dataloader))

22


In [ ]:

class LanguageModel(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, fc1_size, fc2_size, si_size):
        super(LanguageModel, self).__init__()

        # LSTM layer (stacked LSTM)
        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)

        # Fully connected layers
        self.fc1 = nn.Linear(hidden_size, fc1_size)
        self.fc2 = nn.Linear(fc1_size, fc2_size)
        self.si1 = nn.Linear(fc2_size, si_size)
        self.si2 = nn.Linear(si_size, si_size)

        # Output layer with 5 neurons
        self.output_layer = nn.Linear(si_size, 5)

        # Activation functions
        self.relu = nn.ReLU()
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        # LSTM layer
        lstm_out, _ = self.lstm(x)

        fc1_out = self.relu(self.fc1(lstm_out[:, -1, :]))
        fc2_out = self.relu(self.fc2(fc1_out))

        si1 = self.relu(self.si1(fc2_out))
        si2 = self.relu(self.si2(si1))

        # Output layer with sigmoid activation
        output = self.sigmoid(self.output_layer(si2))

        return output

In [ ]:
# model parameters

#LSTM parameters
input_size = 300 # since each word is in GloVe embedding format
hidden_size = 128 # hyperparameter for each LSTM layer. refers to the dimension of the hidden state value
num_layers=1

fc1_size = 128
fc2_size = 128
si_size=128

model = LanguageModel(input_size, hidden_size,num_layers, fc1_size, fc2_size,si_size)

print(model)


LanguageModel(
  (lstm): LSTM(300, 128, batch_first=True)
  (fc1): Linear(in_features=128, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=128, bias=True)
  (si1): Linear(in_features=128, out_features=128, bias=True)
  (si2): Linear(in_features=128, out_features=128, bias=True)
  (output_layer): Linear(in_features=128, out_features=5, bias=True)
  (relu): ReLU()
  (sigmoid): Sigmoid()
)


In [ ]:
loss_fn = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(list(model.parameters())[2:], lr=0.00006)
num_epochs = 150


In [ ]:
# Training loop
for epoch in range(num_epochs):
    # Set model to training mode
    model.train()

    # Initialize variables for epoch loss and accuracy calculation
    total_loss = 0.0
    correct_predictions_train = 0
    total_predictions_train = 0

    # Iterate over the training dataset
    for inputs, labels in train_text_dataloader:
        # Zero the gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(inputs)

        # Calculate loss
        loss = loss_fn(outputs, labels)

        # Backward pass
        loss.backward()

        # Update weights
        optimizer.step()

        # Accumulate total loss
        total_loss += loss.item()

        # Convert outputs to one-hot format
        predicted_labels_train = (outputs >= 0.5).float()

        # Count correct predictions
        correct_predictions_train += (predicted_labels_train == labels).all(dim=1).sum().item()

        # Update total samples
        total_predictions_train += labels.size(0)

    # Calculate average loss for the epoch
    average_loss = total_loss / len(train_text_dataloader)

    # Calculate training accuracy
    train_accuracy = correct_predictions_train / total_predictions_train

    # Validation
    model.eval()  # Set the model to evaluation mode
    with torch.no_grad():
        correct_predictions_val = 0
        total_predictions_val = 0

        # Iterate over the validation dataset
        for inputs, labels in val_text_dataloader:
            outputs = model(inputs)
            predicted_labels_val = (outputs >= 0.5).float()
            correct_predictions_val += (predicted_labels_val == labels).all(dim=1).sum().item()
            total_predictions_val += labels.size(0)

        # Calculate validation accuracy
        val_accuracy = correct_predictions_val / total_predictions_val

    # Print epoch information
    print(f'Epoch [{epoch+1}/{num_epochs}], Training Loss: {average_loss:.4f}, Training Accuracy: {train_accuracy:.4f}, Validation Accuracy: {val_accuracy:.4f}')


Epoch [1/50], Training Loss: 1.5931, Training Accuracy: 0.2822, Validation Accuracy: 0.3178
Epoch [2/50], Training Loss: 1.5834, Training Accuracy: 0.2822, Validation Accuracy: 0.3178
Epoch [3/50], Training Loss: 1.5890, Training Accuracy: 0.2822, Validation Accuracy: 0.3178
Epoch [4/50], Training Loss: 1.5891, Training Accuracy: 0.2822, Validation Accuracy: 0.3178
Epoch [5/50], Training Loss: 1.5931, Training Accuracy: 0.2822, Validation Accuracy: 0.3178
Epoch [6/50], Training Loss: 1.5899, Training Accuracy: 0.2822, Validation Accuracy: 0.3178
Epoch [7/50], Training Loss: 1.5918, Training Accuracy: 0.2822, Validation Accuracy: 0.3178
Epoch [8/50], Training Loss: 1.5924, Training Accuracy: 0.2822, Validation Accuracy: 0.3178
Epoch [9/50], Training Loss: 1.5923, Training Accuracy: 0.2822, Validation Accuracy: 0.3178
Epoch [10/50], Training Loss: 1.5923, Training Accuracy: 0.2822, Validation Accuracy: 0.3178
Epoch [11/50], Training Loss: 1.5889, Training Accuracy: 0.2822, Validation Acc

In [ ]:
# Evaluation on test dataset
model.eval()  # Set the model to evaluation mode
with torch.no_grad():
    correct_predictions_test = 0
    total_predictions_test = 0

    # Iterate over the test dataset
    for inputs, labels in test_text_dataloader:
        outputs = model(inputs)
        predicted_labels_test = (outputs >= 0.5).float()
        correct_predictions_test += (predicted_labels_test == labels).all(dim=1).sum().item()
        total_predictions_test += labels.size(0)

    # Calculate test accuracy
    test_accuracy = correct_predictions_test / total_predictions_test

# Print test accuracy
print(f'Test Accuracy: {test_accuracy:.4f}')


Test Accuracy: 0.1778


In [ ]:
model_path = '/content/drive/My Drive/languagemodel.pt'
torch.save(model.state_dict(), model_path)
